/* FTN Local encrypted file format v2 — chunked AES-GCM encryption. */
(()=>{
  const CHUNK=1024*1024, te=new TextEncoder();
  const b64=u8=>btoa(String.fromCharCode(...u8));
  const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
  async function key(pass,salt){return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},await crypto.subtle.importKey('raw',te.encode(pass),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
  function ivFor(prefix,index){const iv=new Uint8Array(12);iv.set(prefix);new DataView(iv.buffer).setUint32(8,index,false);return iv}
  function aad(size,chunkSize,index){return te.encode('FTN-FILE-AES-GCM|2|'+size+'|'+chunkSize+'|'+index)}
  async function encrypt(file,pass,onProgress){if(!file)throw Error('File required');const salt=crypto.getRandomValues(new Uint8Array(16)),prefix=crypto.getRandomValues(new Uint8Array(8)),k=await key(pass,salt),count=Math.ceil(file.size/CHUNK),chunks=[];for(let i=0;i<count;i++){const data=new Uint8Array(await file.slice(i*CHUNK,Math.min(file.size,(i+1)*CHUNK)).arrayBuffer());const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:ivFor(prefix,i),additionalData:aad(file.size,CHUNK,i)},k,data);chunks.push(b64(new Uint8Array(cipher)));onProgress?.((i+1)/count)}const pkg={format:'FTN-FILE-AES-GCM',version:2,name:file.name,type:file.type||'application/octet-stream',size:file.size,chunkSize:CHUNK,chunkCount:count,salt:b64(salt),noncePrefix:b64(prefix),chunks};return new Blob([JSON.stringify(pkg)],{type:'application/json'})}
  async function decrypt(blob,pass,onProgress){const pkg=JSON.parse(await blob.text());if(pkg.format!=='FTN-FILE-AES-GCM'||pkg.version!==2)throw Error('Unsupported FTN v2 attachment');if(!Number.isSafeInteger(pkg.size)||pkg.size<0||pkg.chunkSize!==CHUNK||!Number.isSafeInteger(pkg.chunkCount)||pkg.chunkCount!==Math.ceil(pkg.size/pkg.chunkSize)||!Array.isArray(pkg.chunks)||pkg.chunks.length!==pkg.chunkCount)throw Error('Invalid FTN v2 package');const k=await key(pass,unb64(pkg.salt)),prefix=unb64(pkg.noncePrefix),parts=[];let total=0;for(let i=0;i<pkg.chunks.length;i++){const data=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:ivFor(prefix,i),additionalData:aad(pkg.size,pkg.chunkSize,i)},k,unb64(pkg.chunks[i])));parts.push(data);total+=data.byteLength;onProgress?.((i+1)/pkg.chunkCount)}if(total!==pkg.size)throw Error('Attachment integrity check failed');return {blob:new Blob(parts,{type:pkg.type||'application/octet-stream'}),name:pkg.name||'decrypted-file',type:pkg.type||'application/octet-stream',size:total}}
  window.FTNFileV2={CHUNK,encrypt,decrypt};
})();
